version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: phonica-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: phonica_user
      POSTGRES_PASSWORD: phonica_password
      POSTGRES_DB: phonica_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U phonica_user -d phonica_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: phonica-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: {} 
